-- avoria.products definition

-- Drop table

-- DROP TABLE avoria.products;

CREATE TABLE avoria.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar NOT NULL,
	sku varchar NOT NULL,
	price numeric NULL,
	stock_quantity int4 NULL,
	is_active bool DEFAULT true NOT NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	CONSTRAINT products_pk PRIMARY KEY (id)
);


-- avoria.orders definition

-- Drop table

-- DROP TABLE avoria.orders;

CREATE TABLE avoria.orders (
	id int8 NOT NULL,
	customer_name varchar NOT NULL,
	customer_email varchar NOT NULL,
	status varchar NULL,
	total_amount numeric NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	CONSTRAINT orders_pk PRIMARY KEY (id)
);


-- avoria.order_items definition

-- Drop table

-- DROP TABLE avoria.order_items;

CREATE TABLE avoria.order_items (
	id int8 GENERATED ALWAYS AS IDENTITY NOT NULL,
	order_id int8 NOT NULL,
	product_id int8 NOT NULL,
	quantity int4 NOT NULL,
	unit_price numeric NOT NULL,
	sub_total numeric NOT NULL,
	CONSTRAINT order_items_orders_fk FOREIGN KEY (id) REFERENCES avoria.orders(id),
	CONSTRAINT order_items_products_fk FOREIGN KEY (id) REFERENCES avoria.products(id)
);